### ISSUE TITLE
Launching

### ISSUE THREAD

**Issue by ImCloudmixer** [Frodeluren/DECtalk-Twitch-TTS-bot#1]
Hey so i was able to get this up and running with some minor edits. But Say.exe seems to stop working without reason after about 10 minutes of uptime. No error or crash. Just stops outputting audio.

**Comment by frodekp** [comment]
Fixed with e8d6947e4f9d36be0ad9744405635ea15e6715bf and 1d328de6cf16ea61f35ce309b75da6a427e04cb9.
