### ISSUE TITLE
Installing Requirements

### ISSUE THREAD

**Issue by SupaCanoli** [Frodeluren/DECtalk-Twitch-TTS-bot#6]
I can get set up requirements in a command prompt with python 3.10, but once i try running the final file (dectalktwitchtts.py), it says that there is no module named "keyboard".

**Comment by SupaCanoli** [comment]
Also looked back in the command prompt and saw that after running `python -m pip install -r requirements.txt`, I got a return somewhere down the line of 'running setup.py install for simpleaudio ... error'. I've added a photo of what it looks like right after I run that command. 

![image](https://user-images.githubusercontent.com/120522250/208558239-b21088a2-a1c6-4508-b1fb-9eb967a63e4b.png)

**Comment by frodekp** [comment]
I tested installing the requirements and running dectalktwitchtts.py with success in a fresh enviroment with Python 3.10.9. So I'm not able to recreate the issue. But I looked up the error message that says `Microsoft Visual C++ 14.0 or greater is reqired...` and found a stackoverflow with a similar issue that might lead to a solution for you https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required/44953739#44953739.

**Comment by SupaCanoli** [comment]
That fixed it, but I just wanted to know if there's a way to make it also say the name of the person who said the chat message or is that yet to be implemented?

**Comment by frodekp** [comment]
I just added this feature in 1e3ad2236ecf7fe1248a3cb0e58e0e84134d4eba. You only need to update `dectalktwitchtts.py` and `config.py` and make sure `SAY_USERNAME` is set to `True`

**Comment by SupaCanoli** [comment]
Okay, thank you very much!
