### ISSUE TITLE
Full message ignoring?

### ISSUE THREAD

**Issue by SupaCanoli** [Frodeluren/DECtalk-Twitch-TTS-bot#7]
I've seen that it's possible to ignore part of a person's message with the text-to-speech bot, but is it possible to ignore full messages, like ones that start with an exclamation mark for commands?

**Comment by frodekp** [comment]
I implemented a filter list that uses regex.
Here is instructions on how to update and how to filter `!command` messages:
1. Update `dectalktwitchtts.py`
2. Add line in config.py: `REGEX_FILTER_PATH = 'regexfilter.txt',`
3. Create new file called `regexfilter.txt`
4. Write `^!(.*)` in `regexfilter.txt` to mute commands
5. If you want to mute the whole message that contains the word `example`. add a line with `(.*)example(.*)` in `regexfilter.txt`
